import { getSettings, HISTORY_KEY } from '../src/defaults.js';
const TABS = [['meaning','含义'],['aesthetic','美学'],['evidence','依据'],['json','JSON']];
const listEl = document.getElementById('list'); let expanded = null; let eagleEnabled = false;
function toast(message){const node=document.createElement('div');node.className='toast';node.textContent=message;document.body.append(node);setTimeout(()=>node.remove(),1500)}
async function copy(value){try{await navigator.clipboard.writeText(value);toast('已复制')}catch{toast('复制失败')}}
function fullText(r={}){return [`一句话结论：\n${r.summary||''}`,`画面内容：\n${r.literal_description||''}`,`核心表达：\n${r.core_meaning||''}`,`整体美学：\n${r.aesthetic?.overall||''}`,`色彩：\n${r.aesthetic?.color||''}`,`构图：\n${r.aesthetic?.composition||''}`,`光线：\n${r.aesthetic?.lighting||''}`,`质感：\n${r.aesthetic?.texture||''}`,`不确定性：\n${r.uncertainty||''}`].join('\n\n')}
function tabText(r,tab){if(tab==='json')return JSON.stringify(r||{},null,2);if(tab==='aesthetic')return [r.aesthetic?.overall,...(r.aesthetic?.style_tags||[]),r.aesthetic?.color,r.aesthetic?.composition,r.aesthetic?.lighting,r.aesthetic?.texture].filter(Boolean).join('\n\n');if(tab==='evidence')return(r.visual_evidence||[]).map(x=>`${x.dimension}\n看到什么：${x.observation}\n如何理解：${x.interpretation}`).join('\n\n');return fullText(r)}
function eagleItem(item){const r=item.result||{};const tags=[...(r.keywords||[]),...(r.aesthetic?.style_tags||[]),'Cuelet','图像含义'];return{url:item.srcUrl,name:r.summary||'图像含义解读',website:item.pageUrl||'',tags:[...new Set(tags.filter(Boolean))].slice(0,20),annotation:fullText(r)}}
async function saveEagle(item){const response=await chrome.runtime.sendMessage({type:'PC_EAGLE_SAVE',item:eagleItem(item)}).catch(()=>({ok:false,error:'后台无响应'}));toast(response?.ok?'已存入 Eagle':`存入失败：${response?.error||'未知错误'}`)}
function timeAgo(ts){const seconds=Math.floor((Date.now()-ts)/1000);if(seconds<60)return'刚刚';if(seconds<3600)return`${Math.floor(seconds/60)} 分钟前`;if(seconds<86400)return`${Math.floor(seconds/3600)} 小时前`;return`${Math.floor(seconds/86400)} 天前`}
function download(name,mime,text){const url=URL.createObjectURL(new Blob([text],{type:mime}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
async function history(){const stored=await chrome.storage.local.get(HISTORY_KEY);return Array.isArray(stored[HISTORY_KEY])?stored[HISTORY_KEY]:[]}
function csv(list){const headers=['time','analysisType','srcUrl','pageUrl','summary','literal_description','core_meaning','aesthetic','emotion','symbolism','alternative_readings','keywords','uncertainty'];const esc=v=>/[",\n]/.test(String(v??''))?`"${String(v??'').replace(/"/g,'""')}"`:String(v??'');return [headers.join(','),...list.map(item=>{const r=item.result||{};return[new Date(item.ts).toISOString(),'meaning',item.srcUrl,item.pageUrl,r.summary,r.literal_description,r.core_meaning,JSON.stringify(r.aesthetic||{}),JSON.stringify(r.emotion||[]),JSON.stringify(r.symbolism||[]),JSON.stringify(r.alternative_readings||[]),JSON.stringify(r.keywords||[]),r.uncertainty].map(esc).join(',')})].join('\n')}
function detail(item){const box=document.createElement('div');box.className='detail';let tab='meaning';const tabs=document.createElement('div');tabs.className='tabs';const content=document.createElement('div');content.className='content';function paint(){[...tabs.children].forEach((button,i)=>button.classList.toggle('active',TABS[i][0]===tab));content.textContent=tabText(item.result||{},tab)||'暂无内容'}TABS.forEach(([key,label])=>{const button=document.createElement('button');button.className='tab';button.textContent=label;button.onclick=e=>{e.stopPropagation();tab=key;paint()};tabs.append(button)});const acts=document.createElement('div');acts.className='acts';const action=(label,fn,primary=false)=>{const b=document.createElement('button');b.textContent=label;if(primary)b.className='primary';b.onclick=e=>{e.stopPropagation();fn()};acts.append(b)};action('复制当前',()=>copy(tabText(item.result||{},tab)),true);action('复制完整分析',()=>copy(fullText(item.result)));action('打开原图',()=>item.srcUrl&&chrome.tabs.create({url:item.srcUrl}));if(eagleEnabled)action('存入 Eagle',()=>saveEagle(item));action('删除',async()=>{const next=(await history()).filter(x=>x.id!==item.id);await chrome.storage.local.set({[HISTORY_KEY]:next});expanded=null;renderHistory()});box.append(tabs,content,acts);paint();return box}
async function renderHistory(){const list=await history();listEl.textContent='';if(!list.length){const empty=document.createElement('div');empty.className='empty';empty.textContent='还没有记录。点击“选图解读含义”，或直接在网页图片上右键分析。';listEl.append(empty);return}list.forEach(item=>{const row=document.createElement('div');row.className='row';const img=document.createElement('img');img.src=item.thumb||'';img.alt='';const info=document.createElement('div');info.className='info';const summary=document.createElement('div');summary.className='summary';summary.textContent=item.result?.summary||'图像含义解读';const when=document.createElement('div');when.className='when';when.textContent=timeAgo(item.ts);info.append(summary,when);row.append(img,info);row.onclick=()=>{expanded=expanded===item.id?null:item.id;renderHistory()};listEl.append(row);if(expanded===item.id)listEl.append(detail(item))})}
async function renderStatus(){const settings=await getSettings();eagleEnabled=!!settings.eagleEnabled;const node=document.getElementById('status');node.className=`status ${settings.apiKey?'ok':'bad'}`;node.textContent=settings.apiKey?`接口已配置 · ${settings.model||'未填写模型'}`:'尚未配置 API Key，请先打开设置'}
document.getElementById('pick').onclick=async()=>{const[tab]=await chrome.tabs.query({active:true,currentWindow:true});if(!tab?.id)return;const response=await chrome.runtime.sendMessage({type:'PC_PICK_PAGE',tabId:tab.id});if(response?.ok)window.close();else toast(response?.error||'无法在此页面运行')};
document.getElementById('settings').onclick=()=>chrome.runtime.openOptionsPage();document.getElementById('shortcuts').onclick=()=>chrome.tabs.create({url:'chrome://extensions/shortcuts'});document.getElementById('about').onclick=()=>chrome.tabs.create({url:chrome.runtime.getURL('welcome.html')});document.getElementById('clear').onclick=async()=>{await chrome.storage.local.set({[HISTORY_KEY]:[]});expanded=null;renderHistory()};document.getElementById('exportJson').onclick=async()=>{const list=await history();if(list.length)download('cuelet-meaning-history.json','application/json',JSON.stringify(list,null,2));else toast('没有历史可导出')};document.getElementById('exportCsv').onclick=async()=>{const list=await history();if(list.length)download('cuelet-meaning-history.csv','text/csv;charset=utf-8','﻿'+csv(list));else toast('没有历史可导出')};
await renderStatus();await renderHistory();
