import { getSettings, saveSettings, PRESETS, MEANING_PROMPT_TEMPLATE } from '../src/defaults.js';
import { testConnection } from '../src/api.js';
const $=id=>document.getElementById(id);const provider=$('provider');Object.entries(PRESETS).forEach(([value,item])=>{const option=document.createElement('option');option.value=value;option.textContent=item.label;provider.append(option)});
function values(){return{provider:provider.value,baseUrl:$('baseUrl').value.trim(),apiKey:$('apiKey').value.trim(),model:$('model').value.trim(),maxDim:Number($('maxDim').value)||1024,maxTokens:Number($('maxTokens').value)||3000,jsonMode:$('jsonMode').checked,meaningPromptTemplate:$('meaningPromptTemplate').value,eagleEnabled:$('eagleEnabled').checked,eagleUrl:$('eagleUrl').value.trim()||'http://localhost:41595',eagleToken:$('eagleToken').value.trim(),eagleFolderId:$('eagleFolder').value,eagleFolderName:$('eagleFolder').selectedOptions[0]?.textContent||''}}
async function load(){const s=await getSettings();provider.value=s.provider;$('baseUrl').value=s.baseUrl;$('apiKey').value=s.apiKey;$('model').value=s.model;$('maxDim').value=s.maxDim;$('maxTokens').value=s.maxTokens;$('jsonMode').checked=s.jsonMode;$('meaningPromptTemplate').value=s.meaningPromptTemplate;$('eagleEnabled').checked=s.eagleEnabled;$('eagleUrl').value=s.eagleUrl;$('eagleToken').value=s.eagleToken;await loadFolders(s.eagleFolderId,s.eagleFolderName)}
provider.onchange=()=>{const preset=PRESETS[provider.value];if(provider.value!=='custom'){$('baseUrl').value=preset.baseUrl;$('model').value=preset.model}};$('resetPrompt').onclick=()=>{$('meaningPromptTemplate').value=MEANING_PROMPT_TEMPLATE};$('save').onclick=async()=>{await saveSettings(values());$('saved').textContent='已保存';setTimeout(()=>$('saved').textContent='',1600)};
$('test').onclick=async()=>{const node=$('testStatus');node.textContent='测试中…';try{await testConnection(values());node.textContent='连接成功'}catch(error){node.textContent=`连接失败：${error.message}`}};
$('testEagle').onclick=async()=>{const response=await chrome.runtime.sendMessage({type:'PC_EAGLE_TEST',eagleUrl:$('eagleUrl').value.trim(),token:$('eagleToken').value.trim()});$('testStatus').textContent=response?.ok?`Eagle 已连接 ${response.version||''}`:`Eagle 连接失败：${response?.error||'未知错误'}`};
async function loadFolders(selected='',name=''){const select=$('eagleFolder');select.textContent='';const root=document.createElement('option');root.value='';root.textContent='根目录';select.append(root);if(name&&selected){const old=document.createElement('option');old.value=selected;old.textContent=name;select.append(old);select.value=selected}}
$('folders').onclick=async()=>{const response=await chrome.runtime.sendMessage({type:'PC_EAGLE_FOLDERS',eagleUrl:$('eagleUrl').value.trim(),token:$('eagleToken').value.trim()});if(!response?.ok)return $('testStatus').textContent=`读取失败：${response?.error||'未知错误'}`;const select=$('eagleFolder');select.textContent='';[{id:'',name:'根目录'},...response.folders].forEach(item=>{const option=document.createElement('option');option.value=item.id;option.textContent=item.name;select.append(option)});$('testStatus').textContent='文件夹已刷新'};
await load();
